services:
  # Main application service
  app:
    image: hpcie-harbornode.pune.cdac.in/bigleap/bigleap-api:latest
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/users"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
