apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigleap
  labels:
    app: bigleap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigleap
  template:
    metadata:
      labels:
        app: bigleap
    spec:
      containers:
      - name: bigleap
        image: hpcie-harbornode.pune.cdac.in/bigleap/bigleap-api
        ports:
        - containerPort: 3000  # This is correct - the container listens on 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"