apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigleap
  labels:
    app: bigleap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bigleap
  template:
    metadata:
      labels:
        app: bigleap
    spec:
      containers:
      - name: bigleap
        image: 10.208.209.242/bigleap/bigleap-api@sha256:cbbefcb136c126448146e67ad855fc8a3cf064be3a02cd59b60e030f6c156b89  # Replace with your actual image
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"