apiVersion: v1
kind: Service
metadata:
  name: bigleap
  labels:
    app: bigleap
spec:
  type: LoadBalancer
  ports:
  - port: 3008        # External port (what users will access)
    targetPort: 3000    # Internal port (what your container exposes)
    protocol: TCP
    name: http
  selector:
    app: bigleap        # This must match the labels in your deployment