apiVersion: v1
kind: Service
metadata:
  name: bigleap
  labels:
    app: bigleap
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: bigleap